export const Routes = {
  MainStackComponent: 'MainStackComponent',
  RootStackContainer: 'RootStackContainer',
  HomeScreen: 'HomeScreen',
  ListProductScreen: 'ListProductScreen',
  ProductDetailsScreen: 'ProductDetailsScreen',
  CartScreen: 'CartScreen',
  OrderScreen: 'OrderScreen',
  TrackOrderScreen: 'TrackOrderScreen',
  TrackOrderDetailsScreen: 'TrackOrderDetailsScreen',
  ChatScreen: 'ChatScreen',
  ChatDetailsScreen: 'ChatDetailsScreen',
  ForumScreen: 'ForumScreen',
  PortfolioScreen: 'PortfolioScreen',
  PortfolioDetailsScreen: 'PortfolioDetailsScreen',
  NotificationScreen: 'NotificationScreen',
  UserScreen: 'UserScreen',
  Preload: 'Preload',
  ModalStackComponent: 'ModalStackComponent',
  BottomStackScreen: 'BottomStackScreen',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  ClassesScreen: 'ClassesScreen',
  OnboardScreen: 'OnboardScreen',
  EditInformationScreen: 'EditInformationScreen',
  ChangePassword: 'ChangePasswordScreen',
  DeleteUser: 'DeleteUser',
  TopicScreen: 'ModalTopicScreen',
  GuideCodeScreen: 'ModalGuideCodeScreen',
  AddressScreen: 'ModalAddressScreen',
  YourPostsScreen: 'YourPostsScreen',
  BlogDetailScreen: 'BlogDetailScreen',
  BlogScreen: 'BlogScreen',
  SearchScreen: 'SearchScreen',
  OfflineScreen: 'OfflineScreen',
  VoucherScreen: 'VoucherScreen',
  SearchModal: 'SearchModal',
  CategoryScreen: 'CategoryScreen',
  SaleCodeScreen: 'SaleCodeScreen',
};

export const ModalRoutes = {
  AddAddressModal: 'AddAddressModal',
  ModalStackComponent: 'ModalStackComponent',
  FilterProductModal: 'FilterProductModal',
  PaymentMethodModal: 'PaymentMethodModal',
  CouponModal: 'CouponModal',
  ReviewsModal: 'ReviewsModal',
  VoucherBrandModal: 'VoucherBrandModal',
};
